name: Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  smoke-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [18, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm test
